import Head from "next/head"
import style from '../styles/layout.module.css'
import Menu from "./menu"
import ShoppingCart from "./shoppingCart"

const Layout = ({children,title}) => {
  return (
    <div>
          <Head>
              <title>GitHub Store {title ? `| ${title}`:''}</title>
              <meta name="description" content="Generated by create next app" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <link rel="icon" href="/favicon.ico" />
          </Head>
          <Menu/>
        <div className={style.container}>
            {children}
            <ShoppingCart/>
        </div>
    </div>
  )
}

export default Layout